# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hO5fagwsRzoAOE8WRhJD-norV12QgGaD
"""

import random
import sys

wins = 0
losses = 0
ties = 0

while True:
  print(f"{wins} Wins, {losses} Losses, {ties} Ties")

  # --- Input Validation Loop ---

  while True:
    print('Enter your moves: r (rock), p (paper), s (scissors) or q (quit) to quit the game')
    player_move = input('')

    if player_move == 'q':
      sys.exit()

    if player_move == 'r' or player_move == 'p' or player_move == 's':
      break

    else:
        print('Please use a valid letter: r, p, s, or q. Thanks!')

  if player_move == 'r':
    print('Rock versus')
  elif player_move == 'p':
    print('Paper versus')
  elif player_move == 's':
    print('Scissors versus')

  move_num = random.randint(1,3)
  if move_num == 1:
    comp_move = 'r'
    print('Rock')
  elif move_num == 2:
    comp_move = 'p'
    print('Paper')
  elif move_num == 3:
    comp_move = 's'
    print('Scissors')

  # --- Game Logic ---

  if player_move == comp_move:
    print('It is a tie!')
    ties += 1

  elif player_move == 'r' and comp_move == 's':
     print('Rock beats Scissors, You lose!')
     wins += 1

  elif player_move == 'r' and comp_move == 'p':
     print('Paper beats Rock , You win!')
     losses += 1

  elif player_move == 'p' and comp_move == 's':
     print('Scissors beats Paper, You lose!')
     losses += 1

  elif player_move == 'p' and comp_move == 'r':
      print('Paper beats Rock, You win!')
      wins += 1

  elif player_move == 's' and comp_move == 'p':
    print('Scissors beats Paper, You win!')
    wins += 1

  elif player_move == 's' and comp_move == 'r':
    print('Rock beats Scissors, You win!')
    losses += 1